/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:143724f7-dfe1-4ca9-b176-6967a981051d",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_DnYYoe9lV",
    "aws_user_pools_web_client_id": "48nfq7aht1g6b323ie30vomrmd",
    "oauth": {},
    "aws_user_files_s3_bucket": "profilepage2913040d9d374f9da1d143c1a86fc89e222010-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1"
};


export default awsmobile;
